### ISSUE TITLE
Incorrect opacity for stackable items numbers

### ISSUE THREAD

**Issue by ghost** [InsomniaKitten/SmartHUD#16]
The issue happens when I'm not using shaders as well.

> 	Minecraft Version: 1.12.2
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 1.8.0_25, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 482703584 bytes (460 MB) / 1023410176 bytes (976 MB) up to 2147483648 bytes (2048 MB)
> 	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
> 	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
> 	FML: MCP 9.42 Powered by Forge 14.23.1.2555 Optifine OptiFine_1.12.2_HD_U_C6

Here's a screenshot:
![2017-12-22_16 43 03](https://user-images.githubusercontent.com/11262717/34303906-d04edb2a-e737-11e7-9c07-d4f6f6802b91.png)

**Comment by ChloeDawn** [comment]
Does this happen without OptiFine installed?
