### ISSUE TITLE
Allow specifying duplicate merging per item

### ISSUE THREAD

**Issue by build2stone** [InsomniaKitten/SmartHUD#18]
This would allow having multiple clocks and compasses in ones inventory and having only one of each display, while simultaneously displaying for example multiple of the same type of flux capacitor with varying levels of charge.

**Comment by ChloeDawn** [comment]
Duplicate merging can now be overriden per-item in the whitelist. Any without their behaviour defined will still use the global config in `modules.cfg`. I'll hopefully have some time to write some documentation on the item whitelist later. A new build will be pushed to CurseForge later today.
