### ISSUE TITLE
Fancy Block Particles Preventing Pickup HUD From Rendering

### ISSUE THREAD

**Issue by Drag0nsaver** [InsomniaKitten/SmartHUD#19]
If you have Fancy Block Particles and SmartHUD installed at the same time, the item pickup readout from SmartHUD will not show. When you toggle Fancy Block Particles off through the in game options, SmartHUD's item pickup readout is visible once more.

> Steps to reproduce issue:
Only need Fancy Block particles and SmartHUD installed. If Fancy Block Particles are enabled, the item pickup readout which would be in the lower left is just gone. Disabling Fancy Block Particles will return visibility of the Item Pickup.

MC Version: 1.12.2 
Fancy Block Particles Version: 2.4.0
SmartHUD Version: 2.0.2
Forge Version: 14.23.4.2729

I have also submitted this information to Fancy Block Particles's issue tracker [https://github.com/TominoCZ/FancyBlockParticles/issues/94](https://github.com/TominoCZ/FancyBlockParticles/issues/94)

**Comment by ChloeDawn** [comment]
I've briefly looked into this and have not discovered the immediate cause. I'll do some more testing and ask around to see if anyone can spot anything that I'm overlooking. My guess right now is some sort of GL leak. Although I don't think the issue is on my end, I'll keep this ticket open until it's figured out.

**Comment by TominoCZ** [comment]
I did a little test and it's kinda strange. SmartHUD seems to be unable to spawn another pickup HUD aftger replacing the effectRenderer with mine.. It still renders the same right after I replace the particle manager so idk what could be wrong here...

**Comment by ChloeDawn** [comment]
After deliberating the possible solutions, I've come to the decision that it is not viable for me to fix this on my end. FBP is far too intrusive with how and when it replaces the particle manager. That and 1.12 is an old version, I do not want to spend an extensive amount of time on mod compatibility for my final 1.12 release, sorry.

**Comment by TominoCZ** [comment]
Yeahh probably for the better.
