### ISSUE TITLE
Toggle rounded borders?

### ISSUE THREAD

**Issue by ghost** [InsomniaKitten/SmartHUD#2]
![2017-06-24_12 19 37](https://user-images.githubusercontent.com/11262717/27507943-0fdc3d14-58db-11e7-810d-1b6657d744ef.png)

Do you think it's possible? I'd like the same design as the main hotbar. Nice mod btw, I'm loving it! :)

**Comment by ChloeDawn** [comment]
This will be added in the next release, thank you for the suggestion ^^

**Comment by ChloeDawn** [comment]
Added in [1.12-1.0.2](https://minecraft.curseforge.com/projects/smart-hud/files/2440735) and [1.11.2-1.0.1](https://minecraft.curseforge.com/projects/smart-hud/files/2440736)
