### ISSUE TITLE
Smart HUD Causing High CPU-Load According to LagGoggles

### ISSUE THREAD

**Issue by Luke616** [InsomniaKitten/SmartHUD#21]
Hello,

Been using LagGoggles as a tool to diagnose CPU inefficiencies and laggy processes in my pack, and I've identified smartHUD as a mod which consistently reports a disproportionately large CPU load.

![2019-02-17_21 32 56](https://user-images.githubusercontent.com/3951604/54711275-f51e8c00-4b1f-11e9-8ae6-ad0083f61ff9.png)

I know that LagGoggles is not a substitute for a proper CPU profiling program, please let me know if there's any more information I can provide. Lag reports attributing a large amount of tick time to SmartHUD are very common, this one was recorded in SSP.

Versions:
Minecraft 1.12.2
Smart HUD 2.0.2.jar
Forge 14.23.5.2815

Hope this helps!
- Luke616

**Comment by ChloeDawn** [comment]
Can you provide reproduction steps? What were your inventory contents at the time of profiling?
