### ISSUE TITLE
hotbar swap incompatibility

### ISSUE THREAD

**Issue by rayblon** [InsomniaKitten/SmartHUD#22]
When hotbar swap is installed and the compass/clock is swapped into the hotbar, Smart Hud begins bugging out with the clock and compass slots constantly rendering and derendering.

**Comment by ChloeDawn** [comment]
What is "hotbar swap"? Can you provide a link?

**Comment by rayblon** [comment]
My bad, it's called hotswap. https://minecraft.curseforge.com/projects/hotswap
