### ISSUE TITLE
Add x and y offset to positioning [1.12.2]

### ISSUE THREAD

**Issue by lerokko** [InsomniaKitten/SmartHUD#26]
I have a hotbar mod and a lot of other HUD mods. Right now Smart HUD is partly behind another HUD element. I'd like to move it up a little or sideways, perhaps also align it with a corner of the screen (plus offset). Otherwise the mod is sadly unusable for me :/

**Comment by ChloeDawn** [comment]
I don't think I will be introducing this feature, sorry. I've considered it but it would be too much work to refactor the current code, which is very focused on supporting left-handed primary hands and the hot bar attack cooldown indicator. Adding support for moving the HUD would mean rewriting this implementation to be more dynamic and context-aware. If someone wants to contribute this feature themselves, they are more than welcome to, however.
