### ISSUE TITLE
Regional slots - Overworld, Nether, End

### ISSUE THREAD

**Issue by ghost** [InsomniaKitten/SmartHUD#3]
Since the clock and the compass are the most common items to use with this mod, it would be great to have the slots with these items disabled in the Nether (only) where they are useless! You should add a toggle in the whitelist to hide specific items when the player is the overworld, or nether or end.

![2017-06-24_16 12 52](https://user-images.githubusercontent.com/11262717/27509222-284ddeda-58f8-11e7-8f8b-668f2417fe76.png)

**Comment by ChloeDawn** [comment]
I could add dimension ID whitelisting. So you would define `minecraft:clock@0` to whitelist the clock for dimension 0 (the overworld), or `minecraft:clock@0,1` to whitelist it for dimensions 0 and 1 (the overworld and the end), for example.

**Comment by ghost** [comment]
It should work for now but in the future you'll have to make it simpler, just for noob users. I like it like this

**Comment by ChloeDawn** [comment]
I try to describe the configs in as much detail as possible within the file (and in-game config when you mouse-over the labels). Any new features will be self-explanatory and I have no intention of dumbing down configuration for "noob users", sorry.

**Comment by ghost** [comment]
whatever you'll decide is fine for me  ¯\_(ツ)_/¯
keep up the good work
